#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains 
#     the string `Ceci n'est pas une page`.

sudo apt-get update -y
sudo apt-get install -y nginx
sudo chmod -R 777 /var/www
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo service nginx start
