#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02 using roundrobin

sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y
sudo apt-get update -y
sudo apt-get install haproxy=2.0.\.* -y

sudo chmod 777 /etc/haproxy/haproxy.cfg
echo -e "frontend http\n\tbind *:80\n\tmode http\n\tdefault_backend myservers\n" >> /etc/haproxy/haproxy.cfg
echo -e "backend myservers\n\tbalance roundrobin\n\tmode http\n\tserver web1 3.236.59.72:80 check\n\tserver web2 35.175.130.170:80 check" >> /etc/haproxy/haproxy.cfg
sudo chmod 644 /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy
